hwi_oauth:
    connect:
        account_connector: my.custom.user_provider

    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_reso  urce_owners.md
    resource_owners:
        vk:
            type:                vkontakte
            client_id:           '%env(VK_ID)%'
            client_secret:       '%env(VK_SECRET)%'
#            scope:               "email"
#            options:
#                display: popup
#                csrf: true

    fosub:
        username_iterations: 30
        properties:
            vk:    vkId